### PR TITLE
Fix the travis setup to use Zombie 3 and add PHP 7

### PR DESCRIPTION
**Pull request by stof**
Refs #133 (it does not add the job for Zombie 4, but it does other changes for now)

### CODE REVIEW

**Comment by aik099** [comment]
I would rather split this into 2 PR's: "adding PHP 7" and "using Zombie 3 by default".

**Comment by stof** [comment]
is it really worth it ? The PR is ready right now

**Comment by aik099** [comment]
It's changes to same file at the end, but I usually like to create on topic PR's instead of mixing unrelated changes to same file in single PR. Maybe this time we can have combined PR to get green Travis build faster.

**Comment by stof** [comment]
I suggest merging this as is rather than splitting it into 2 conflicting PRs (because yes, there would be conflicts between them as they would change adjacent lines). We need a green build

**Comment by aik099** [comment]
Sure. As I'm said in https://github.com/minkphp/MinkZombieDriver/pull/137#issuecomment-115609505 I agree with you.

**Comment by stof** [comment]
OK, merging this now

**Pull request merged**
