### PR TITLE
Honor DriverInterface::wait() spec

### PR DESCRIPTION
**Pull request by 1ma**
Addresses issue [#147](https://github.com/minkphp/MinkZombieDriver/issues/147)

### CODE REVIEW

**Comment by stof** [comment]
Can you first add a test reproducing the issue in the driver testsuite in Mink, so that we ensure that all drivers actually respect it ?

**Comment by 1ma** [comment]
Alright, will do.

What about the failing CookieTest::testCookieWithSemicolon? Apparently it is already broken at upstream/master.

**Comment by aik099** [comment]
> What about the failing CookieTest::testCookieWithSemicolon? Apparently it is already broken at upstream/master.

It is. In https://github.com/minkphp/Mink/pull/680 there is duscussion in which we've decided to update all drivers to manually escape user provided cookie value (as browser does), but this never got implemented hence the failing test.

**Comment by stof** [comment]
OK, I sent the PR adding the test

**Pull request merged**
